### PR TITLE
adding additional_json_data param

### PR DESCRIPTION
**Pull request by rockaut**
##### SUMMARY
see #101 

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
grafana_datasource

##### ADDITIONAL INFORMATION
```paste below
- name: Create postgres datasource
  grafana_datasource:
    name: "datasource-postgres"
    grafana_url: "https://grafana.company.com"
    grafana_user: "admin"
    grafana_password: "xxxxxx"
    org_id: "1"
    ds_type: "postgres"
    ds_url: "postgres.company.com:5432"
    database: "db"
    user: "postgres"
    password: "iampgroot"
    sslmode: "verify-full"
    additional_json_data:
      timescaledb: false
```

### CODE REVIEW

**Comment by seuf** [comment]
Hi, Thanks for you rour PR.
If I understand well, the new field `additional_json_data` allow to add custom payload in jsonData datasource (in case of some fields are not yet managed by the ansible datasource module), but any field added in this parameter could be overrided by the others (like `zabbix_user`)

**Comment by rockaut** [comment]
@seuf exactly. The module parameter itself is defaulted to an empty dict at first hand. In the function a variable is created with this content and in the further proceedings all keys are set on this function. So it's perfectly backward compatible and even future proof for further module parameters as long the keys are set after the first lines.

**Comment by rockaut** [comment]
@rrey @seuf 

Question as I'm currently working on getting secureJsonData incorporated as well. Is it correct, that if tlsAuth is used (which uses secureJsonData) every ansible run is changed=True? I know this is kind of obvious because secureJsonData and secureDataFields can't be compared. I just wanted to check-back if I'm not doing anything wrong.

**Comment by seuf** [comment]
> Is it correct, that if tlsAuth is used (which uses secureJsonData) every ansible run is changed=True? I know this is kind of obvious because secureJsonData and secureDataFields can't be compared. I just wanted to check-back if I'm not doing anything wrong.

Yes, Grafana API does not return content of `secureJsonData` (which is secure :) ) so it can't be compared and the module have to override this with the user's values.
Maybe a parameter `ignore_secure_json_data_change` that allow to skip this comparaison and return changed false  can be added.
I merge this PR now, so you can create a new one with additional secure json data.

**Pull request merged**
