### PR TITLE
Copy ignore-2.12.txt to ignore-2.13.txt

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Relates to https://github.com/ansible-collections/overview/issues/45#issuecomment-926794724

### CODE REVIEW

**Comment by rrey** [comment]
Ho :/ devel seems to now require Python >= 3.8
This will need an adaptation of the matrix I guess

**Comment by Andersson007** [comment]
> Ho :/ devel seems to now require Python >= 3.8 This will need an adaptation of the matrix I guess

adjusted

**Comment by Andersson007** [comment]
@rrey now integration tests are failing, could you please take a look?

**Comment by rrey** [comment]
Seems that ssh-keygen is required by devel as well now. That’s new, seems weird to me

**Comment by gundalow** [comment]
> Seems that ssh-keygen is required by devel as well now. That’s new, seems weird to me

I've asked internal, I didn't know this had changed.

I've got a PR to add `--requirements` to ansible-test, let's see if that fixes it, though I think this option might only install Python dependencies.. https://github.com/ansible-collections/community.grafana/pull/188

**Comment by Andersson007** [comment]
@rrey @gundalow CI looks green now, we could merge this, thanks!

**Comment by Andersson007** [comment]
@rrey @seuf can we merge this one?

**Comment by rrey** [comment]
Thanks @Andersson007 !

**Pull request merged**
