### PR TITLE
grafana_dashboard: add new option json string (import)

### PR DESCRIPTION
**Pull request by CWollinger**
##### SUMMARY

Add a new option to grafana_dashboard.
Able to import grafana dashboard via a string.

With this option you are able to lookup files on the local system, save them into a variable and import them to a remote grafana server.

This allows to execute the module on a remote system if you have (only) the possibility to connect via ssh instead of http.

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME

grafana_dashboard

##### ADDITIONAL INFORMATION

Example play:
```paste below
---
- hosts: all
  collections:
    - community.grafana
  tasks:
  - name: Export dashboard
    grafana_dashboard:
      grafana_url: http://localhost:3000
      grafana_api_key: "..."
      state: present
      commit_message: Updated by ansible
      overwrite: yes
      json: "{{ lookup('file', '/home/user/grafana/Q9K5pvrWz.json') }}"

```

### CODE REVIEW

**Comment by rrey** [comment]
Hi @CWollinger,

Why not simply using the copy module a use the module with existing interface ?

**Comment by CWollinger** [comment]
> 
> 
> Hi @CWollinger,
> 
> Why not simply using the copy module a use the module with existing interface ?

I use copy at the moment. I thought it could be hlpful in gerneral. E.g. if you edit or use the json in the play for another task.

**Comment by rrey** [comment]
@CWollinger I would prefer not to to include that feature if we have a standard way to achieve things with ansible modules.
I suggest that we close the PR and see if people are upvoting or asking to reopen it.

Is that ok for you ?

**Comment by CWollinger** [comment]
@rrey yes, sure 👍

**Pull request closed without merging**
