### PR TITLE
support elasticsearch version 6.0+, 7.0+

### PR DESCRIPTION
**Pull request by CWollinger**
##### SUMMARY
You are able to select es version 6.0+ and 7.0+ in the grafana GUI.
This change will support this via the ansible module.

##### ISSUE TYPE
- Feature Pull Request

##### COMPONENT NAME
grafana_datasource

### CODE REVIEW

**Comment by rrey** [comment]
Hi @CWollinger !

I saw that your PR fails because of new sanity requirements, I made the fix here: https://github.com/ansible-collections/community.grafana/pull/96

You patch should be mergeable after it is merged and your PR rebased.

Thanks for contributing !

**Comment by seuf** [comment]
#96 is merged. Can you rebase please ?

**Comment by rrey** [comment]
The sanity errors are weird, you did not change these files. Please rebase with master to have only your additional commit on the PR.

**Comment by CWollinger** [comment]
> 
> 
> The sanity errors are weird, you did not change these files. Please rebase with master to have only your additional commit on the PR.



> 
> 
> The sanity errors are weird, you did not change these files. Please rebase with master to have only your additional commit on the PR.



> 
> 
> The sanity errors are weird, you did not change these files. Please rebase with master to have only your additional commit on the PR.

I removed the other commits and made a fresh commit. But still failing... Strange

**Comment by rrey** [comment]
ha ! 
@gundalow the `ignore-2.10.txt` seems to have lost its effect on our collection, is there a change around this ?

**Comment by gundalow** [comment]
Yup, devel is now 2.11, so you'll need to copy the file ignore-2.11.txt

**Comment by rrey** [comment]
@gundalow what would we do without you !

@CWollinger I fixed the ignore here: https://github.com/ansible-collections/community.grafana/pull/97 and I added the rebase action.

**Comment by CWollinger** [comment]
> 
> 
> /rebase

Failed again.. https://github.com/ansible-collections/community.grafana/actions/runs/146368522

**Comment by rrey** [comment]
@CWollinger can you copy the `ignore-2.10.txt` from `tests/sanity` as `ignore-2.11.txt` ? It should disable the sanity issue.

**Comment by rrey** [comment]
Thanks for your patch @CWollinger !

**Pull request merged**
