### PR TITLE
fix(tests): fix usage of unsafe conditional

### PR DESCRIPTION
**Pull request by rrey**
Variable expension in conditionals is now forbidden. porting guide is here: https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_9.html#playbook

##### SUMMARY

tests fails with following error:
```
fatal: [testhost]: FAILED! => {"msg": "The conditional check 'result.msg == 'Dashboard {{ result.uid }} deleted'' failed. The error was: Conditional is marked as unsafe, and cannot be evaluated."}
```

Applying a fix based on porting guide.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
grafana_dashboard

### CODE REVIEW

**Comment by rrey** [comment]
`grafana_dashboard` do not return a status `changed` when importing a dashboard from url.

**Comment by rrey** [comment]
This is not a regression introduced by the Grafana version bumped.

**Comment by Nemental** [comment]
I think this is already covered in #331 
Can be closed?

**Comment by Nemental** [comment]
Conflicts resolved, no changes left, all integration checks successful -> closed

**Pull request closed without merging**
