### PR TITLE
fix: bump required ansible version to 2.15.0

### PR DESCRIPTION
**Pull request by Nemental**
##### SUMMARY

bump required ansible version to 2.15.0
##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

```paste below

```

### CODE REVIEW

**Comment by rndmh3ro** [comment]
Why exactly is 2.15 needed?

**Comment by Nemental** [comment]
@rndmh3ro 
https://github.com/ansible-collections/community.grafana/actions/runs/9302156010/job/25601790520#step:3:222
Or do you mean why not 2.16.0 because it's the official current version?

**Comment by rndmh3ro** [comment]
This rule seems rather controversial: https://github.com/ansible/ansible-lint/issues/3950

I'm fine with merging this, but I have to ask. Is removing support for an older ansible-version only a patch or rather a minor/major release? Idk.

**Comment by Nemental** [comment]
@rndmh3ro I think it's okay because it requires an already unmaintained version (2.15.0) anyway and not the official current version (2.16.0). Imo users should be aware that such issues may occur when using an unmaintained version.

**Comment by Nemental** [comment]
@rndmh3ro You're right, trivial doesn't fit in this case. Maybe we can go with breaking_changes as 2.0.0 is on the way? #375

**Comment by rndmh3ro** [comment]
Well, if we release this with 2.0.0 I don't see a problem.

**Review by rndmh3ro — APPROVED** [review]

**Pull request merged**
