### PR TITLE
fix: check if login exists in grafana organization user exists check

### PR DESCRIPTION
**Pull request by rustyb**
##### SUMMARY

Nice collection much appreciated.

I noticed a small bug in the organisation user exists check when using v1.6.0.

When you add a user to an organisation you provide the login name. Once the user is created in the organisation and you run the task again you always get the error message `Exception: [BUG] User not found in organization`

I had not defined names on the users I created so the check was not finding them as the `name` field of each user was `''`.

This brought me to [`_organization_user_by_login`](https://github.com/ansible-collections/community.grafana/blob/2202c99c0e24d8bce9346959af79c67aaf1a4610/plugins/modules/grafana_organization_user.py#L179C4-L183) which is only checking the `name` and `email` fields.

I've updated the check to also check `login` against the `login` field of the user.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

Issue with `grafana_organization_user` -> [`_organization_user_by_login`](https://github.com/ansible-collections/community.grafana/blob/2202c99c0e24d8bce9346959af79c67aaf1a4610/plugins/modules/grafana_organization_user.py#L179C4-L183).

##### ADDITIONAL INFORMATION

I had an existing grafana initalised with several users and was attempting to add new organisations and place users within them. I used the following tasks list. First run goes well. Subsequent runs fail at `"Add user to the organization"` due to the name field being empty on my users.

```yml
---
    - name: Create a Grafana organization
      community.grafana.grafana_organization:
        url: "{{ grafana_url }}"
        url_username: "{{ grafana_security.admin_user }}"
        url_password: "{{ grafana_security.admin_password  }}"
        name: cbr test
        state: present 
      register: org
   
    - name: Add user to the organization
      community.grafana.grafana_organization_user:
        url: "{{ grafana_url }}"
        url_username: "{{ grafana_security.admin_user }}"
        url_password: "{{ grafana_security.admin_password  }}"
        org_id: "{{ org.org.id }}"
        login: "cbr"
        role: admin
        state: present
```

### CODE REVIEW

**Comment by Nemental** [comment]
Hi! I just stumbled over your issue and noticed that I ran into the same problem as you in my PR (https://github.com/ansible-collections/community.grafana/pull/318). Unlike in your solution, I didn't include the “name” attribute in the query because, according to the API, it is not included in the login check.
https://grafana.com/docs/grafana/latest/developers/http_api/org/#add-user-in-organization
`loginOrEmail` - The user's name field is not used when logging in.

**Comment by rustyb** [comment]
@Nemental had completely forgot about this one. Yes indeed it seems like the solution in your PR would also work for my use case too.

**Comment by rrey** [comment]
@rustyb can you chack that your issue is fixed now that @Nemental's patch is merged ? 🙏

**Comment by rustyb** [comment]
@rrey I can confirm that #318 solves my issue - feel free to close this PR 👍

**Comment by rrey** [comment]
Awesome !

**Pull request closed without merging**
