### PR TITLE
check cmd result on uninstall

### LINKED ISSUE #103: Error "plugin does not exist" on state: absent
##### SUMMARY
If a plugin is removed with `state: absent` a second run will throw an error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
grafana_plugin

##### ANSIBLE VERSION

```paste below
ansible 2.10.0rc3
  python version = 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
```

##### CONFIGURATION
```paste below
- name: install plugins
  with_list: "{{ plugins.results }}"
  notify: restart grafana-server
  community.grafana.grafana_plugin:
    name: "{{ item.item.key }}"
    grafana_plugin_url: "{{ item.files[-1].path }}"
    state: absent
    grafana_plugins_dir: "{{ grafana_plugins_dir }}"
    version: "{{ install_grafana_plugins[item.item.key].version }}"
```

##### OS / ENVIRONMENT
Grafana 7.1.1

##### STEPS TO REPRODUCE
- 1st run: install plugin with present
- 2nd run: uninstall plugin with absent
- 3rd run:  uninstall plugin with absent = error

##### EXPECTED RESULTS
Ansible Task result: no change

##### ACTUAL RESULTS
2nd run:
```
changed: [host] ... 'item': {'key': 'camptocamp-prometheus-alertmanager-datasource', 'value': {'url': 'https://grafana.com/api/plugins/camptocamp-prometheus-alertmanager-datasource/versions/0.0.7/download', 'fileglob': 'camptocamp-grafana-prometheus-alertmanager-datasource', 'version': '0.0.7', 'state': 'absent'}}, 'ansible_loop_var': 'item'})
```

3rd run:
```paste below
failed: [host] ... "msg": "'/sbin/grafana-cli --pluginUrl camptocamp-grafana-prometheus-alertmanager-datasource-0.0.7-0-gc4d8c51.zip --pluginsDir /var/lib/grafana/plugins plugins uninstall camptocamp-prometheus-alertmanager-datasource' execution returned an error : [1] Removing plugin: camptocamp-prometheus-alertmanager-datasource\nError: ✗ plugin does not exist\n "}
```

### PR DESCRIPTION
**Pull request by rockaut**
##### SUMMARY
fix #103
also added tests

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
grafana_plugin

### CODE REVIEW

**Comment by rockaut** [comment]
Should I close and reopen to get the stuck CI redone?

**Comment by rockaut** [comment]
Close to Restart hanging CI

**Comment by rockaut** [comment]
@rrey I've let the CI rerun but now I sanity checks are failing for other changes not related to my commit.

**Comment by rrey** [comment]
@rockaut changes can be introduced by upstream ansible-base used in the CI
I’m starting to think we should fix its version ...

**Comment by rockaut** [comment]
sorry... wrongly deleted the branch

**Comment by rockaut** [comment]
close and reopen for CI reruns

**Comment by rockaut** [comment]
@rrey sorry I don't get why this CI/sanity is failing but the one at #108 is not.

**Pull request merged**
