### PR TITLE
ci: fix get latest grafana versions python script

### PR DESCRIPTION
**Pull request by Nemental**
##### SUMMARY

- increase number of returned releases by api to ensure the newest 3 majors are included
- refactor comparation of version numbers
  - work with multi digits major versions
  - compare versions as tulpe not as int
    - before: `10.0.13 (as_int: 10013) > 10.2.6 (as_int: 1026)` (older version is higher)
    - after: `10.0.13 (as_tulpe: (10, 0, 13)) < 10.2.6 (as_tulpe: (10, 2, 6))` (newer version is higher)

##### ISSUE TYPE

- Bugfix Pull Request

##### ADDITIONAL INFORMATION

before:
```
["9.5.18", "10.0.13"]
```

after:
```
["8.5.27", "9.5.18", "10.4.1"]
```

### CODE REVIEW

**Review by rrey — APPROVED** [review]

**Review by rrey — CHANGES_REQUESTED** [review]
I just tried to run the script and got an error:

```
Traceback (most recent call last):
  File "/Users/remirey/dev/ansible_collections/community/grafana/hacking/find_grafana_versions.py", line 30, in <module>
    major, version, as_tuple = get_by_major(release.get("tag_name"))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/remirey/dev/ansible_collections/community/grafana/hacking/find_grafana_versions.py", line 10, in get_by_major
    return int(version.split(".")[0]), version, tuple(map(int, version.split(".")))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '0-preview'

```

**Comment by Nemental** [comment]
They released a preview right after my changes to the python script :D Now all pre-release (-) and build-release tags (+) are skipped according to the semantic version

**Comment by Nemental** [comment]
failed sanity workflow is fixed in #355

**Comment by rndmh3ro** [comment]
lgtm

**Review by rndmh3ro — APPROVED** [review]

**Pull request merged**
